apiVersion: v1
kind: ReplicationController
metadata:
 labels:
 app: solrApp
 name: solr-rc
spec:
 replicas: 2
 selector:
 app: solrApp
 template:
 metadata:
 labels:
 app: solrApp
 spec:
 containers:
 -
 image: solr
 name: solr
 ports:
 -
 containerPort: 8983
 name: solrApp
